[workspace]
members = [
    "crates/rusty_sat_core",
    "crates/rusty_sat_config",
    "crates/rusty_sat_readers",
    "crates/rusty_sat_resample",
    "crates/rusty_sat_composites",
    "crates/rusty_sat_image",
    "crates/rusty_sat_writers",
    "crates/rusty_sat_cli",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/LeonJian/RustySat"

[profile.release]
lto = "thin"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

