[package]
name = "rusty_sat_modifiers"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rusty_sat_core = { path = "../rusty_sat_core" }
rayon = "1.10"
rustyspectral = "1.0"
ndarray = "0.16"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
