[package]
name = "rusty_sat_writers"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
flate2 = "1.0"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
png = "0.18"
rusty_sat_core = { path = "../rusty_sat_core" }
rusty_sat_image = { path = "../rusty_sat_image" }
rusty_sat_resample = { path = "../rusty_sat_resample" }

[lints]
workspace = true
