[package]
name = "rusty_sat_readers"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bzip2 = "0.4"
regex = "1.10"
rusty_sat_core = { path = "../rusty_sat_core" }
serde_norway = "0.9"

[dev-dependencies]
rusty_sat_resample = { path = "../rusty_sat_resample" }
rusty_sat_writers = { path = "../rusty_sat_writers" }
rusty_sat_modifiers = { path = "../rusty_sat_modifiers" }

[[example]]
name = "ahi_first_figure"
path = "examples/ahi_first_figure.rs"

[lints]
workspace = true
